//! Conformance test: the hardcoded pit-diag decoder vs. the AMS DBC.
//!
//! `src/pit_diag/mod.rs` decodes the AMS pit-diag firehose from a
//! **hardcoded** frame layout — fixed IDs, frame counts, per-field bit
//! positions/endianness, and enum value tables. That's deliberate: the
//! decoder is fast and produces richly-typed structs the UI consumes.
//! The risk (flagged during slice 1) is that the AMS firmware changes
//! the wire and we *silently* mis-decode.
//!
//! This test removes the "silently". The AMS DBC (`docs/dbc/ams.dbc`,
//! generated by their `tools/gen_dbc.py`) is the source of truth for
//! the wire. We vendor a snapshot (`src/pit_diag/testdata/ams.dbc`,
//! see PROVENANCE.txt) and assert the decoder's hardcoded assumptions
//! still match it: message IDs, frame counts, the 58-frame total,
//! cell/temp signal shapes, the diag-block endianness subtleties, and
//! the FSM-state / fault-reason / mode-lock enum tables.
//!
//! **When this fails:** the AMS wire changed. Re-vendor `ams.dbc`,
//! read the diff, and reconcile `src/pit_diag/mod.rs` (and these
//! expectations) before shipping. This is the DBC-ingestion safety net
//! for #252 — drift detection without a runtime DBC dependency.

use can_dbc::{ByteOrder, Dbc, MessageId, ValueType};
use can_flasher::pit_diag::{
    AMS_ACK_ID, AMS_ARM_ID, AMS_BALANCE_MASK_A_ID, AMS_BALANCE_MASK_B_ID, AMS_BOOT_DIAG_ID,
    AMS_CELLV_BASE_ID, AMS_CELLV_LAST_ID, AMS_CELLV_NUM_FRAMES, AMS_DIAG_NUM_FRAMES,
    AMS_EXPECTED_FRAMES_PER_SCAN, AMS_FSM_STATUS_ID, AMS_FW_ID_ID, AMS_NTC_BASE_ID,
    AMS_NTC_LAST_ID, AMS_NTC_NUM_FRAMES, AMS_PER_IC_PEC_HI_ID, AMS_PER_IC_PEC_LO_ID,
    AMS_POLL_TIMING_ID, AMS_POST_MORTEM_ID,
};

const AMS_DBC: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/pit_diag/testdata/ams.dbc"
));

fn load() -> Dbc {
    Dbc::try_from(AMS_DBC).expect("vendored ams.dbc must parse")
}

fn msg_id_u32(id: &MessageId) -> u32 {
    match id {
        MessageId::Standard(s) => u32::from(*s),
        MessageId::Extended(e) => *e,
    }
}

/// Frame id of the message named `name`, or panic with a clear message
/// (a renamed/removed message is exactly the drift we want to catch).
fn id_of(dbc: &Dbc, name: &str) -> u32 {
    dbc.messages
        .iter()
        .find(|m| m.name == name)
        .map(|m| msg_id_u32(&m.id))
        .unwrap_or_else(|| panic!("DBC has no message named {name:?} — AMS wire changed?"))
}

fn message<'a>(dbc: &'a Dbc, name: &str) -> &'a can_dbc::Message {
    dbc.messages
        .iter()
        .find(|m| m.name == name)
        .unwrap_or_else(|| panic!("DBC has no message named {name:?}"))
}

// ---- Handshake IDs ----

#[test]
fn cmd_and_ack_ids_match_decoder() {
    let dbc = load();
    assert_eq!(
        id_of(&dbc, "PitDiag_cmd"),
        u32::from(AMS_ARM_ID),
        "PitDiag_cmd id must equal AMS_ARM_ID (0x7F0)"
    );
    assert_eq!(
        id_of(&dbc, "PitDiag_ack"),
        u32::from(AMS_ACK_ID),
        "PitDiag_ack id must equal AMS_ACK_ID (0x7F1)"
    );
}

// ---- Cell-voltage frames: 24 contiguous, 4× BE u16 each ----

#[test]
fn cell_frames_match_decoder_geometry() {
    let dbc = load();
    let mut ids: Vec<u32> = dbc
        .messages
        .iter()
        .filter(|m| m.name.starts_with("PitDiag_cells_"))
        .map(|m| msg_id_u32(&m.id))
        .collect();
    ids.sort_unstable();

    assert_eq!(
        ids.len(),
        AMS_CELLV_NUM_FRAMES,
        "expected {AMS_CELLV_NUM_FRAMES} PitDiag_cells_* frames"
    );
    assert_eq!(*ids.first().unwrap(), u32::from(AMS_CELLV_BASE_ID));
    assert_eq!(*ids.last().unwrap(), u32::from(AMS_CELLV_LAST_ID));
    // Contiguous, no gaps.
    for (offset, id) in ids.iter().enumerate() {
        assert_eq!(*id, u32::from(AMS_CELLV_BASE_ID) + offset as u32);
    }

    // Every cell frame: four 16-bit big-endian unsigned readings (the
    // decoder reads 4× BE u16 mV per frame).
    let first = message(&dbc, "PitDiag_cells_00");
    assert_eq!(first.signals.len(), 4, "each cell frame carries 4 cells");
    for sig in &first.signals {
        assert_eq!(sig.size, 16, "{}: cell readings are 16-bit", sig.name);
        assert_eq!(
            sig.byte_order,
            ByteOrder::BigEndian,
            "{}: cell readings are big-endian",
            sig.name
        );
        assert_eq!(sig.value_type, ValueType::Unsigned, "{}", sig.name);
    }
}

// ---- NTC-temp frames: 25 contiguous, 8× i8 each ----

#[test]
fn temp_frames_match_decoder_geometry() {
    let dbc = load();
    let mut ids: Vec<u32> = dbc
        .messages
        .iter()
        .filter(|m| m.name.starts_with("PitDiag_temps_"))
        .map(|m| msg_id_u32(&m.id))
        .collect();
    ids.sort_unstable();

    assert_eq!(ids.len(), AMS_NTC_NUM_FRAMES, "expected 25 temp frames");
    assert_eq!(*ids.first().unwrap(), u32::from(AMS_NTC_BASE_ID));
    assert_eq!(*ids.last().unwrap(), u32::from(AMS_NTC_LAST_ID));
    for (offset, id) in ids.iter().enumerate() {
        assert_eq!(*id, u32::from(AMS_NTC_BASE_ID) + offset as u32);
    }

    // Eight signed 8-bit °C readings per frame.
    let first = message(&dbc, "PitDiag_temps_00");
    assert_eq!(first.signals.len(), 8, "each temp frame carries 8 NTCs");
    for sig in &first.signals {
        assert_eq!(sig.size, 8, "{}: temps are 8-bit", sig.name);
        assert_eq!(
            sig.value_type,
            ValueType::Signed,
            "{}: temps are i8",
            sig.name
        );
    }
}

// ---- Diag block: 9 frames at the exact IDs the decoder dispatches on ----

#[test]
fn diag_block_ids_and_names_match_decoder() {
    let dbc = load();
    // The decoder dispatches each diag frame by its hardcoded ID; this
    // pins the ID -> message-name mapping to the AMS DBC.
    let expected: &[(u16, &str)] = &[
        (AMS_FSM_STATUS_ID, "PitDiag_fsm_status"),
        (AMS_POLL_TIMING_ID, "PitDiag_timing"),
        (AMS_BALANCE_MASK_A_ID, "PitDiag_balance_mask_a"),
        (AMS_BALANCE_MASK_B_ID, "PitDiag_balance_mask_b"),
        (AMS_BOOT_DIAG_ID, "PitDiag_boot_diag"),
        (AMS_POST_MORTEM_ID, "PitDiag_post_mortem"),
        (AMS_FW_ID_ID, "PitDiag_fw_id"),
        (AMS_PER_IC_PEC_LO_ID, "PitDiag_pec_per_ic_a"),
        (AMS_PER_IC_PEC_HI_ID, "PitDiag_pec_per_ic_b"),
    ];
    assert_eq!(expected.len(), AMS_DIAG_NUM_FRAMES);
    for (id, name) in expected {
        assert_eq!(
            id_of(&dbc, name),
            u32::from(*id),
            "{name} must sit at 0x{id:03X}"
        );
    }
}

#[test]
fn total_pitdiag_stream_is_58_frames() {
    let dbc = load();
    let stream = dbc
        .messages
        .iter()
        .filter(|m| {
            m.name.starts_with("PitDiag_cells_")
                || m.name.starts_with("PitDiag_temps_")
                || matches!(
                    m.name.as_str(),
                    "PitDiag_fsm_status"
                        | "PitDiag_timing"
                        | "PitDiag_balance_mask_a"
                        | "PitDiag_balance_mask_b"
                        | "PitDiag_boot_diag"
                        | "PitDiag_post_mortem"
                        | "PitDiag_fw_id"
                        | "PitDiag_pec_per_ic_a"
                        | "PitDiag_pec_per_ic_b"
                )
        })
        .count();
    assert_eq!(
        stream, AMS_EXPECTED_FRAMES_PER_SCAN,
        "pit-diag scan should be {AMS_EXPECTED_FRAMES_PER_SCAN} frames"
    );
}

// ---- Diag-block endianness subtleties ----
//
// The decoder treats the diag block as little-endian EXCEPT the poll
// latencies and the PEC error total, which are big-endian (the AMS
// firmware packs those with `>> 8`). Pin both sides so a future DBC
// flip of either is caught.

#[test]
fn diag_block_field_endianness_matches_decoder() {
    let dbc = load();

    let sig = |msg: &str, name: &str| -> (u64, ByteOrder) {
        let m = message(&dbc, msg);
        let s = m
            .signals
            .iter()
            .find(|s| s.name == name)
            .unwrap_or_else(|| panic!("{msg} has no signal {name:?}"));
        (s.size, s.byte_order)
    };

    // Big-endian fields.
    assert_eq!(
        sig("PitDiag_fsm_status", "pec_err_total"),
        (16, ByteOrder::BigEndian),
        "pec_err_total is a 16-bit BE count"
    );
    assert_eq!(
        sig("PitDiag_timing", "bms_volt_poll_ms"),
        (16, ByteOrder::BigEndian),
        "poll latency is 16-bit BE"
    );
    assert_eq!(
        sig("PitDiag_timing", "bms_volt_poll_max_ms"),
        (16, ByteOrder::BigEndian)
    );

    // Little-endian fields.
    assert_eq!(
        sig("PitDiag_fsm_status", "fsm_state"),
        (8, ByteOrder::LittleEndian),
        "fsm_state is a single byte at offset 0"
    );
    assert_eq!(
        sig("PitDiag_timing", "temp_sweep_last_mask"),
        (32, ByteOrder::LittleEndian),
        "the sweep bitmask is 32-bit LE"
    );
    assert_eq!(
        sig("PitDiag_boot_diag", "jump_reason"),
        (32, ByteOrder::LittleEndian),
        "jump_reason is a 32-bit LE enum"
    );
}

// ---- Enum value tables ----
//
// The decoder maps these raw values to FsmState / FaultReason /
// ModeLock variants. Encode the expected (value -> name) tables here
// and assert the DBC's VAL_ definitions match — an added/renamed
// fault reason on the AMS side trips this and forces a decoder update.

fn val_table(dbc: &Dbc, msg_id: u16, signal: &str) -> Vec<(i64, String)> {
    let mut v: Vec<(i64, String)> = dbc
        .value_descriptions_for_signal(MessageId::Standard(msg_id), signal)
        .unwrap_or_else(|| panic!("no VAL_ table for {signal} on 0x{msg_id:03X}"))
        .iter()
        .map(|d| (d.id, d.description.clone()))
        .collect();
    v.sort_by_key(|(id, _)| *id);
    v
}

#[test]
fn fsm_state_value_table_matches_decoder() {
    let dbc = load();
    let expected: Vec<(i64, String)> = [
        (0, "Start"),
        (1, "Precharge"),
        (2, "Transition"),
        (3, "Run"),
        (4, "Charge"),
        (5, "Error"),
    ]
    .iter()
    .map(|(i, s)| (*i, s.to_string()))
    .collect();
    assert_eq!(val_table(&dbc, AMS_FSM_STATUS_ID, "fsm_state"), expected);
}

#[test]
fn mode_locked_value_table_matches_decoder() {
    let dbc = load();
    let expected: Vec<(i64, String)> = [(0, "Undecided"), (1, "Car"), (2, "Charger")]
        .iter()
        .map(|(i, s)| (*i, s.to_string()))
        .collect();
    assert_eq!(val_table(&dbc, AMS_FSM_STATUS_ID, "mode_locked"), expected);
}

#[test]
fn fault_reason_value_table_matches_decoder() {
    let dbc = load();
    let expected: Vec<(i64, String)> = [
        (0, "None"),
        (1, "ForceError"),
        (2, "BmsModuleOffline"),
        (3, "BmsStale"),
        (4, "CellUnderVoltage"),
        (5, "CellOverVoltage"),
        (6, "CellUnderTemp"),
        (7, "CellOverTemp"),
        (8, "CurrentSensorFault"),
        (9, "CurrentStale"),
        (10, "CurrentOverLimit"),
        (11, "VcuStale"),
        (12, "FsmError"),
        (13, "TempSensorDisconnected"),
        (14, "ChargerStale"),
    ]
    .iter()
    .map(|(i, s)| (*i, s.to_string()))
    .collect();
    assert_eq!(val_table(&dbc, AMS_FSM_STATUS_ID, "fault_reason"), expected);
}
